/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'tacet.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.android-arm64.node')
          } else {
            nativeBinding = require('@tacet/js-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'tacet.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.android-arm-eabi.node')
          } else {
            nativeBinding = require('@tacet/js-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'tacet.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@tacet/js-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'tacet.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@tacet/js-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'tacet.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@tacet/js-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'tacet.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./tacet.darwin-universal.node')
      } else {
        nativeBinding = require('@tacet/js-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'tacet.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.darwin-x64.node')
          } else {
            nativeBinding = require('@tacet/js-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'tacet.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.darwin-arm64.node')
          } else {
            nativeBinding = require('@tacet/js-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'tacet.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./tacet.freebsd-x64.node')
      } else {
        nativeBinding = require('@tacet/js-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-x64-musl.node')
            } else {
              nativeBinding = require('@tacet/js-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@tacet/js-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@tacet/js-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@tacet/js-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@tacet/js-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@tacet/js-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@tacet/js-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'tacet.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./tacet.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@tacet/js-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'tacet.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./tacet.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@tacet/js-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Calibration, AdaptiveState, calibrateSamples, adaptiveStepBatch, analyze, AttackerModel, Outcome, InconclusiveReason, EffectPattern, Exploitability, MeasurementQuality, rdtsc, calibrateTimer, version, defaultConfig, configAdjacentNetwork, configSharedHardware, configRemoteNetwork } = nativeBinding

module.exports.Calibration = Calibration
module.exports.AdaptiveState = AdaptiveState
module.exports.calibrateSamples = calibrateSamples
module.exports.adaptiveStepBatch = adaptiveStepBatch
module.exports.analyze = analyze
module.exports.AttackerModel = AttackerModel
module.exports.Outcome = Outcome
module.exports.InconclusiveReason = InconclusiveReason
module.exports.EffectPattern = EffectPattern
module.exports.Exploitability = Exploitability
module.exports.MeasurementQuality = MeasurementQuality
module.exports.rdtsc = rdtsc
module.exports.calibrateTimer = calibrateTimer
module.exports.version = version
module.exports.defaultConfig = defaultConfig
module.exports.configAdjacentNetwork = configAdjacentNetwork
module.exports.configSharedHardware = configSharedHardware
module.exports.configRemoteNetwork = configRemoteNetwork
