// Native bindings for @tacet/js
// Generated by napi-rs - do not edit manually
/** Adaptive sampling state. */
export declare class AdaptiveState {
  /** Create a new adaptive state. */
  constructor()
  /** Get total baseline samples collected. */
  get totalBaseline(): number
  /** Get total sample class samples collected. */
  get totalSample(): number
  /** Get current leak probability estimate. */
  get currentProbability(): number
  /** Get the number of batches collected so far. */
  get batchCount(): number
}

/** Opaque calibration state handle. */
export declare class Calibration {

}

/** Run one adaptive step with a new batch of samples. */
export declare function adaptiveStepBatch(calibration: Calibration, state: AdaptiveState, baseline: BigInt64Array, sample: BigInt64Array, config: Config, elapsedSecs: number): AdaptiveStepResult

/** Result of an adaptive step. */
export interface AdaptiveStepResult {
  /** Whether a decision was reached. */
  isDecision: boolean
  /** Current leak probability estimate. */
  currentProbability: number
  /** Samples collected per class so far. */
  samplesPerClass: number
  /** The final result (only valid if is_decision is true). */
  result?: AnalysisResult
}

/** Analysis result. */
export interface AnalysisResult {
  /** Test outcome. */
  outcome: Outcome
  /** Leak probability: P(max_k |delta_k| > theta | data). */
  leakProbability: number
  /** Effect size estimate. */
  effect: EffectEstimate
  /** Measurement quality. */
  quality: MeasurementQuality
  /** Number of samples used per class. */
  samplesUsed: number
  /** Time spent in seconds. */
  elapsedSecs: number
  /** Exploitability (only valid if outcome == Fail). */
  exploitability: Exploitability
  /** Inconclusive reason (only valid if outcome == Inconclusive). */
  inconclusiveReason: InconclusiveReason
  /** Minimum detectable effect in nanoseconds. */
  mdeNs: number
  /** Timer resolution in nanoseconds. */
  timerResolutionNs: number
  /** User's requested threshold (theta) in nanoseconds. */
  thetaUserNs: number
  /** Effective threshold after floor adjustment in nanoseconds. */
  thetaEffNs: number
  /** Recommendation string (empty if not applicable). */
  recommendation: string
  /** Detailed diagnostics. */
  diagnostics: Diagnostics
}

/** Run complete analysis on pre-collected timing data. */
export declare function analyze(baseline: BigInt64Array, sample: BigInt64Array, config: Config, timerFrequencyHz: number): AnalysisResult

/**
 * Attacker model determines the minimum effect threshold (theta) for leak detection.
 *
 * Cycle-based thresholds use a 5 GHz reference frequency (conservative).
 */
export declare enum AttackerModel {
  /** theta = 0.4 ns (~2 cycles @ 5 GHz) - SGX, cross-VM, containers */
  SharedHardware = 0,
  /** theta = 2.0 ns (~10 cycles @ 5 GHz) - Post-quantum crypto */
  PostQuantum = 1,
  /** theta = 100 ns - LAN, HTTP/2 (Timeless Timing Attacks) */
  AdjacentNetwork = 2,
  /** theta = 50 us - General internet */
  RemoteNetwork = 3,
  /** theta -> 0 - Detect any difference (not for CI) */
  Research = 4
}

/**
 * Calibrate timing samples.
 *
 * # Arguments
 * - `baseline` - Baseline timing samples (raw ticks)
 * - `sample` - Sample class timing samples (raw ticks)
 * - `config` - Analysis configuration
 * - `timer_frequency_hz` - Timer frequency in Hz
 */
export declare function calibrateSamples(baseline: BigInt64Array, sample: BigInt64Array, config: Config, timerFrequencyHz: number): Calibration

/**
 * Get timer calibration information.
 *
 * Performs a quick calibration (~100ms) to determine:
 * - `cyclesPerNs` - Timer ticks per nanosecond
 * - `resolutionNs` - Timer resolution in nanoseconds
 * - `frequencyHz` - Timer frequency in Hz
 *
 * # Example (TypeScript)
 * ```typescript
 * const info = calibrateTimer();
 * const elapsedNs = Number(elapsed) / info.cyclesPerNs;
 * ```
 */
export declare function calibrateTimer(): TimerInfo

/** Configuration for the timing analysis. */
export interface Config {
  /** Attacker model to use (determines threshold theta). */
  attackerModel: AttackerModel
  /** Maximum samples per class. 0 = default (100,000). */
  maxSamples: number
  /** Time budget in milliseconds. 0 = default (30,000 ms). */
  timeBudgetMs: number
  /** Pass threshold for leak probability. Default: 0.05. */
  passThreshold: number
  /** Fail threshold for leak probability. Default: 0.95. */
  failThreshold: number
  /** Random seed. None = use system entropy. */
  seed?: number
  /** Custom threshold in nanoseconds (overrides attacker_model). */
  customThresholdNs?: number
}

/** Create a configuration for adjacent network attacker (100ns threshold). */
export declare function configAdjacentNetwork(): Config

/** Create a configuration for remote network attacker (50us threshold). */
export declare function configRemoteNetwork(): Config

/** Create a configuration for shared hardware attacker (0.4ns threshold). */
export declare function configSharedHardware(): Config

/** Create a default configuration for a given attacker model. */
export declare function defaultConfig(attackerModel: AttackerModel): Config

/** Diagnostics information for debugging and quality assessment. */
export interface Diagnostics {
  /** Block length used for bootstrap resampling. */
  dependenceLength: number
  /** Effective sample size accounting for autocorrelation. */
  effectiveSampleSize: number
  /** Ratio of post-test variance to calibration variance. */
  stationarityRatio: number
  /** Whether stationarity check passed. */
  stationarityOk: boolean
  /** Whether discrete mode was used (low timer resolution). */
  discreteMode: boolean
  /** Timer resolution in nanoseconds. */
  timerResolutionNs: number
  /** Posterior mean of latent scale lambda. */
  lambdaMean: number
  /** Whether lambda chain mixed well. */
  lambdaMixingOk: boolean
  /** Posterior mean of likelihood precision kappa. */
  kappaMean: number
  /** Coefficient of variation of kappa. */
  kappaCv: number
  /** Effective sample size of kappa chain. */
  kappaEss: number
  /** Whether kappa chain mixed well. */
  kappaMixingOk: boolean
}

/** Effect size estimate. */
export interface EffectEstimate {
  /** Maximum effect in nanoseconds: max_k |delta_k|. */
  maxEffectNs: number
  /** Lower bound of 95% credible interval for max effect. */
  ciLowNs: number
  /** Upper bound of 95% credible interval for max effect. */
  ciHighNs: number
}

/** Exploitability assessment. */
export declare enum Exploitability {
  /** < 10 ns - Requires shared hardware to exploit. */
  SharedHardwareOnly = 0,
  /** 10-100 ns - Exploitable via HTTP/2 request multiplexing. */
  Http2Multiplexing = 1,
  /** 100 ns - 10 us - Exploitable with standard remote timing. */
  StandardRemote = 2,
  /** > 10 us - Obvious leak, trivially exploitable. */
  ObviousLeak = 3
}

/** Reason for inconclusive result. */
export declare enum InconclusiveReason {
  /** Not applicable (outcome is not Inconclusive). */
  None = 0,
  /** Posterior approximately equals prior after calibration. */
  DataTooNoisy = 1,
  /** Posterior stopped updating despite new data. */
  NotLearning = 2,
  /** Estimated time to decision exceeds budget. */
  WouldTakeTooLong = 3,
  /** Time budget exhausted. */
  TimeBudgetExceeded = 4,
  /** Sample limit reached. */
  SampleBudgetExceeded = 5,
  /** Measurement conditions changed during test. */
  ConditionsChanged = 6,
  /** Threshold was elevated due to measurement noise. */
  ThresholdElevated = 7
}

/** Measurement quality assessment. */
export declare enum MeasurementQuality {
  /** MDE < 5 ns - Excellent measurement precision. */
  Excellent = 0,
  /** MDE 5-20 ns - Good precision. */
  Good = 1,
  /** MDE 20-100 ns - Poor precision. */
  Poor = 2,
  /** MDE > 100 ns - Too noisy for reliable detection. */
  TooNoisy = 3
}

/** Test outcome. */
export declare enum Outcome {
  /** No timing leak detected within threshold theta. */
  Pass = 0,
  /** Timing leak detected exceeding threshold theta. */
  Fail = 1,
  /** Could not reach a decision. */
  Inconclusive = 2,
  /** Operation too fast to measure reliably. */
  Unmeasurable = 3
}

/**
 * Read the CPU cycle counter.
 *
 * This is a very fast operation (~1-2ns overhead) that reads:
 * - x86_64: `lfence; rdtsc` (CPU timestamp counter)
 * - aarch64: `isb; mrs cntvct_el0` (virtual timer count)
 *
 * Returns raw timer ticks as a BigInt. Use `calibrateTimer()` to convert to nanoseconds.
 *
 * # Example (TypeScript)
 * ```typescript
 * const start = rdtsc();
 * myOperation();
 * const elapsed = rdtsc() - start;
 * ```
 */
export declare function rdtsc(): number

/** Timer calibration info. */
export interface TimerInfo {
  /** Cycles per nanosecond. */
  cyclesPerNs: number
  /** Timer resolution in nanoseconds. */
  resolutionNs: number
  /** Timer frequency in Hz. */
  frequencyHz: number
}

/** Get the library version. */
export declare function version(): string
