//! Build script for tacet-c
//!
//! Generates C header file using cbindgen.

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let _package_name = env::var("CARGO_PKG_NAME").unwrap();

    // Create include directory if it doesn't exist
    let include_dir = PathBuf::from(&crate_dir).join("include");
    std::fs::create_dir_all(&include_dir).expect("Failed to create include directory");

    // Generate header using cbindgen
    let output_file = include_dir.join("tacet.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("TACET_H".to_string()),
        pragma_once: false,
        cpp_compat: true,
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::Doxy,
        no_includes: true,
        includes: vec![
            "stdint.h".to_string(),
            "stddef.h".to_string(),
            "stdbool.h".to_string(),
        ],
        header: Some(format!(
            "/**\n\
             * @file tacet.h\n\
             * @brief C API for tacet: Statistical timing side-channel detection\n\
             *\n\
             * This header is auto-generated by cbindgen. Do not edit manually.\n\
             *\n\
             * @section Usage\n\
             *\n\
             * ## One-Shot Analysis\n\
             * 1. Collect timing samples in your own measurement loop\n\
             * 2. Call to_analyze() with baseline and sample arrays\n\
             * 3. Check the result outcome\n\
             *\n\
             * ## Adaptive Sampling Loop\n\
             * 1. Collect calibration samples (5000 recommended)\n\
             * 2. Call to_calibrate() to get calibration data\n\
             * 3. Create state with to_state_new()\n\
             * 4. In a loop: collect batches, call to_step(), check for decision\n\
             * 5. Free resources with to_state_free() and to_calibration_free()\n\
             */\n"
        )),
        after_includes: None,
        trailer: None,
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(&output_file);

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/types.rs");
    println!(
        "cargo:rustc-env=GENERATED_HEADER={}",
        output_file.display()
    );
}
